<a href="https://colab.research.google.com/github/SushiOnToast/fpl-dashboard/blob/main/fpl_dashboard.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import requests
import json
import pandas as pd
import plotly.io as pio
pio.renderers.default = "colab"

In [3]:
response = requests.get("https://fantasy.premierleague.com/api/bootstrap-static/")
data_dict = json.loads(response.text)

for key, value in data_dict.items():
  print(key)

chips
events
game_settings
game_config
phases
teams
total_players
element_stats
element_types
elements

In [4]:
elements_df = pd.DataFrame(data_dict['elements'])
elements_df

,can_transact,can_select,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,price_change_percent,...,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90,defensive_contribution_per_90
0,True,True,NaN,NaN,154561,0,0,1,-1,91.6,...,1,27,2,22,1,6,1,1.00,0.57,0.00
1,True,True,NaN,NaN,109745,0,0,-1,1,-71.6,...,15,537,68,591,70,460,54,0.00,0.00,0.00
2,True,True,NaN,NaN,437495,0,0,-1,1,-66.9,...,18,546,71,595,71,548,63,0.00,0.00,0.00
3,True,True,NaN,NaN,226597,0,0,-1,1,-5.5,...,1,54,14,49,17,15,4,1.00,0.57,8.29
4,True,True,100.0,100.0,445122,0,0,0,0,24.9,...,2,274,93,438,154,211,82,0.58,0.00,4.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
663,True,True,100.0,100.0,638411,0,0,0,0,0.1,...,126,295,107,576,207,611,207,0.84,0.00,4.21
664,True,True,NaN,NaN,696104,0,0,0,0,-94.1,...,280,297,133,354,157,322,113,0.00,0.00,3.60
665,True,True,NaN,NaN,549940,0,0,0,0,-74.5,...,97,339,159,411,195,538,218,0.00,0.00,6.98
666,True,True,NaN,NaN,661313,0,0,0,0,6.9,...,78,296,36,353,38,202,31,0.00,0.00,0.00
667,True,True,NaN,NaN,604211,0,0,0,0,0.0,...,193,247,113,388,179,665,297,1.55,0.00,4.66

In [5]:
for column in elements_df.columns:
  print(column)

can_transact
can_select
chance_of_playing_next_round
chance_of_playing_this_round
code
cost_change_event
cost_change_event_fall
cost_change_start
cost_change_start_fall
price_change_percent
price_change_hourly_rate
price_change_projections
price_change_locked_until
price_change_calibrating
dreamteam_count
element_type
ep_next
ep_this
event_points
first_name
form
id
in_dreamteam
news
news_added
now_cost
photo
points_per_game
removed
second_name
selected_by_percent
special
squad_number
status
team
team_code
total_points
transfers_in
transfers_in_event
transfers_out
transfers_out_event
value_form
value_season
web_name
known_name
region
team_join_date
birth_date
has_temporary_code
opta_code
minutes
goals_scored
assists
clean_sheets
goals_conceded
own_goals
penalties_saved
penalties_missed
yellow_cards
red_cards
saves
bonus
bps
influence
creativity
threat
ict_index
clearances_blocks_interceptions
recoveries
tackles
defensive_contribution
starts
expected_goals
expected_assists
expected_goal_involvements
expected_goals_conceded
corners_and_indirect_freekicks_order
corners_and_indirect_freekicks_text
direct_freekicks_order
direct_freekicks_text
penalties_order
penalties_text
scout_risks
scout_news_link
influence_rank
influence_rank_type
creativity_rank
creativity_rank_type
threat_rank
threat_rank_type
ict_index_rank
ict_index_rank_type
expected_goals_per_90
saves_per_90
expected_assists_per_90
expected_goal_involvements_per_90
expected_goals_conceded_per_90
goals_conceded_per_90
now_cost_rank
now_cost_rank_type
form_rank
form_rank_type
points_per_game_rank
points_per_game_rank_type
selected_rank
selected_rank_type
starts_per_90
clean_sheets_per_90
defensive_contribution_per_90

In [6]:
keep = [
    # identity
    "id", "code", "web_name", "first_name", "second_name", "team", "team_code", "element_type",

    # price and value
    "now_cost", "cost_change_start", "value_form", "value_season",

    # performance
    "total_points", "points_per_game", "form", "event_points",
    "minutes", "starts", "goals_scored", "assists", "clean_sheets",
    "goals_conceded", "saves", "bonus", "bps",
    "yellow_cards", "red_cards", "own_goals",
    "penalties_saved", "penalties_missed", "defensive_contribution",

    # underlying stats
    "expected_goals", "expected_assists", "expected_goal_involvements",
    "expected_goals_conceded", "influence", "creativity", "threat", "ict_index",

    # ownership and transfers
    "selected_by_percent", "transfers_in", "transfers_out",
    "transfers_in_event", "transfers_out_event",

    # availability
    "status", "news", "news_added",
    "chance_of_playing_this_round", "chance_of_playing_next_round",

    # set pieces
    "penalties_order", "corners_and_indirect_freekicks_order", "direct_freekicks_order",

    # FPL's own predictions
    "ep_this", "ep_next",
]

players = elements_df[keep].copy()
players

,id,code,web_name,first_name,second_name,team,team_code,element_type,now_cost,cost_change_start,...,status,news,news_added,chance_of_playing_this_round,chance_of_playing_next_round,penalties_order,corners_and_indirect_freekicks_order,direct_freekicks_order,ep_this,ep_next
0,1,154561,Raya,David,Raya Martín,1,3,1,61,1,...,a,,None,NaN,NaN,NaN,NaN,NaN,6.0,6.0
1,2,109745,Arrizabalaga,Kepa,Arrizabalaga Revuelta,1,3,1,49,-1,...,a,,None,NaN,NaN,NaN,NaN,NaN,0.0,0.0
2,3,437495,Meslier,Illan,Meslier,1,3,1,49,-1,...,a,,None,NaN,NaN,NaN,NaN,NaN,0.0,0.0
3,4,226597,Gabriel,Gabriel,dos Santos Magalhães,1,3,2,79,-1,...,a,,None,NaN,NaN,NaN,NaN,NaN,5.0,5.0
4,5,445122,J.Timber,Jurriën,Timber,1,3,2,65,0,...,a,,2026-07-23T12:01:23.272929Z,100.0,100.0,NaN,NaN,NaN,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
663,612,638411,Methalie,Dayann,Méthalie,20,56,2,45,0,...,a,,2026-08-28T13:00:08.950445Z,100.0,100.0,NaN,NaN,NaN,0.5,0.5
664,613,696104,Ahoka,Jules,Ahoka,20,56,3,45,0,...,a,,None,NaN,NaN,NaN,NaN,NaN,0.5,0.5
665,646,549940,Fofana,Malick,Fofana,20,56,3,55,0,...,a,,None,NaN,NaN,NaN,NaN,NaN,0.5,0.5
666,651,661313,J.Angulo,Juan,Angulo,20,56,4,45,0,...,a,,None,NaN,NaN,NaN,NaN,NaN,0.5,0.5
667,668,604211,Tutierov,Tymur,Tutierov,20,56,3,50,0,...,a,,None,NaN,NaN,NaN,NaN,NaN,1.6,1.6

In [7]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 668 entries, 0 to 667
Data columns (total 54 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   id                                    668 non-null    int64
 1   code                                  668 non-null    int64
 2   web_name                              668 non-null    object
 3   first_name                            668 non-null    object
 4   second_name                           668 non-null    object
 5   team                                  668 non-null    int64
 6   team_code                             668 non-null    int64
 7   element_type                          668 non-null    int64
 8   now_cost                              668 non-null    int64
 9   cost_change_start                     668 non-null    int64
 10  value_form                            668 non-null    object
 11  value_season                          668 non-null    object
 12  total_points                          668 non-null    int64
 13  points_per_game                       668 non-null    object
 14  form                                  668 non-null    object
 15  event_points                          668 non-null    int64
 16  minutes                               668 non-null    int64
 17  starts                                668 non-null    int64
 18  goals_scored                          668 non-null    int64
 19  assists                               668 non-null    int64
 20  clean_sheets                          668 non-null    int64
 21  goals_conceded                        668 non-null    int64
 22  saves                                 668 non-null    int64
 23  bonus                                 668 non-null    int64
 24  bps                                   668 non-null    int64
 25  yellow_cards                          668 non-null    int64
 26  red_cards                             668 non-null    int64
 27  own_goals                             668 non-null    int64
 28  penalties_saved                       668 non-null    int64
 29  penalties_missed                      668 non-null    int64
 30  defensive_contribution                668 non-null    int64
 31  expected_goals                        668 non-null    object
 32  expected_assists                      668 non-null    object
 33  expected_goal_involvements            668 non-null    object
 34  expected_goals_conceded               668 non-null    object
 35  influence                             668 non-null    object
 36  creativity                            668 non-null    object
 37  threat                                668 non-null    object
 38  ict_index                             668 non-null    object
 39  selected_by_percent                   668 non-null    object
 40  transfers_in                          668 non-null    int64
 41  transfers_out                         668 non-null    int64
 42  transfers_in_event                    668 non-null    int64
 43  transfers_out_event                   668 non-null    int64
 44  status                                668 non-null    object
 45  news                                  668 non-null    object
 46  news_added                            350 non-null    object
 47  chance_of_playing_this_round          323 non-null    float64
 48  chance_of_playing_next_round          350 non-null    float64
 49  penalties_order                       63 non-null     float64
 50  corners_and_indirect_freekicks_order  88 non-null     float64
 51  direct_freekicks_order                67 non-null     float64
 52  ep_this                               668 non-null    object
 53  ep_next                               668 non-null    object
dtypes: float64(5), int64(28), object(21)
memory usage: 281.9+ KB

In [8]:
players["price"] = players["now_cost"] / 10

In [9]:
to_num_cols = ["value_form", "value_season", "points_per_game", "form", "expected_goals", "expected_assists", "expected_goal_involvements", "expected_goals_conceded", "influence", "creativity", "threat", "ict_index", "selected_by_percent", "ep_this", "ep_next"]

for col in to_num_cols:
  players[col] = pd.to_numeric(players[col])

players["news_added"] = pd.to_datetime(players["news_added"])

In [10]:
teams_df = pd.DataFrame(data_dict["teams"])
teams_df

,code,draw,form,id,loss,name,played,points,position,short_name,...,unavailable,win,link_url,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,2,ARS,...,False,0,,4,5,0,0,0,0,1
1,7,0,None,2,0,Aston Villa,0,0,12,AVL,...,False,0,,3,3,0,0,0,0,2
2,91,0,None,3,0,Bournemouth,0,0,15,BOU,...,False,0,,3,3,0,0,0,0,127
3,94,0,None,4,0,Brentford,0,0,6,BRE,...,False,0,,3,3,0,0,0,0,130
4,36,0,None,5,0,Brighton,0,0,3,BHA,...,False,0,,3,4,0,0,0,0,131
5,8,0,None,6,0,Chelsea,0,0,4,CHE,...,False,0,,4,4,0,0,0,0,4
6,9,0,None,7,0,Coventry City,0,0,17,COV,...,False,0,,2,2,0,0,0,0,5
7,31,0,None,8,0,Crystal Palace,0,0,14,CRY,...,False,0,,2,3,0,0,0,0,6
8,11,0,None,9,0,Everton,0,0,8,EVE,...,False,0,,3,3,0,0,0,0,7
9,54,0,None,10,0,Fulham,0,0,18,FUL,...,False,0,,2,3,0,0,0,0,34
10,88,0,None,11,0,Hull City,0,0,9,HUL,...,False,0,,2,2,0,0,0,0,41
11,40,0,None,12,0,Ipswich Town,0,0,10,IPS,...,False,0,,2,2,0,0,0,0,8
12,2,0,None,13,0,Leeds,0,0,7,LEE,...,False,0,,3,3,0,0,0,0,9
13,14,0,None,14,0,Liverpool,0,0,5,LIV,...,False,0,,4,4,0,0,0,0,10
14,43,0,None,15,0,Man City,0,0,1,MCI,...,False,0,,4,5,0,0,0,0,11
15,1,0,None,16,0,Man Utd,0,0,13,MUN,...,False,0,,4,4,0,0,0,0,12
16,4,0,None,17,0,Newcastle,0,0,11,NEW,...,False,0,,3,3,0,0,0,0,23
17,17,0,None,18,0,Nott'm Forest,0,0,19,NFO,...,False,0,,3,3,0,0,0,0,15
18,6,0,None,19,0,Spurs,0,0,16,TOT,...,False,0,,2,3,0,0,0,0,21
19,56,0,None,20,0,Sunderland,0,0,20,SUN,...,False,0,,3,3,0,0,0,0,29

In [11]:
element_types_df = pd.DataFrame(data_dict["element_types"])
element_types_df

,id,plural_name,plural_name_short,singular_name,singular_name_short,squad_select,squad_min_select,squad_max_select,squad_min_play,squad_max_play,ui_shirt_specific,sub_positions_locked,element_count
0,1,Goalkeepers,GKP,Goalkeeper,GKP,2,None,None,1,1,True,[12],73
1,2,Defenders,DEF,Defender,DEF,5,None,None,3,5,False,[],217
2,3,Midfielders,MID,Midfielder,MID,5,None,None,2,5,False,[],299
3,4,Forwards,FWD,Forward,FWD,3,None,None,1,3,False,[],79

In [12]:
teams_small = teams_df[["id", "name", "short_name"]]
players = pd.merge(
    players,
    teams_small,
    left_on="team",
    right_on="id",
    how="left",
    suffixes=("", "_team")
)

element_types_small = element_types_df[["id", "singular_name", "singular_name_short"]]
players = pd.merge(
    players,
    element_types_small,
    left_on="element_type",
    right_on="id",
    how="left",
    suffixes=("", "_type")
)

players = players.drop(columns=["id_team", "id_type"])
players = players.rename(
    columns={
        "name": "team_name",
        "short_name": "team_name_short",
        "singular_name": "position",
        "singular_name_short": "position_short"
    }
)

players

,id,code,web_name,first_name,second_name,team,team_code,element_type,now_cost,cost_change_start,...,penalties_order,corners_and_indirect_freekicks_order,direct_freekicks_order,ep_this,ep_next,price,team_name,team_name_short,position,position_short
0,1,154561,Raya,David,Raya Martín,1,3,1,61,1,...,NaN,NaN,NaN,6.0,6.0,6.1,Arsenal,ARS,Goalkeeper,GKP
1,2,109745,Arrizabalaga,Kepa,Arrizabalaga Revuelta,1,3,1,49,-1,...,NaN,NaN,NaN,0.0,0.0,4.9,Arsenal,ARS,Goalkeeper,GKP
2,3,437495,Meslier,Illan,Meslier,1,3,1,49,-1,...,NaN,NaN,NaN,0.0,0.0,4.9,Arsenal,ARS,Goalkeeper,GKP
3,4,226597,Gabriel,Gabriel,dos Santos Magalhães,1,3,2,79,-1,...,NaN,NaN,NaN,5.0,5.0,7.9,Arsenal,ARS,Defender,DEF
4,5,445122,J.Timber,Jurriën,Timber,1,3,2,65,0,...,NaN,NaN,NaN,1.0,1.0,6.5,Arsenal,ARS,Defender,DEF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
663,612,638411,Methalie,Dayann,Méthalie,20,56,2,45,0,...,NaN,NaN,NaN,0.5,0.5,4.5,Sunderland,SUN,Defender,DEF
664,613,696104,Ahoka,Jules,Ahoka,20,56,3,45,0,...,NaN,NaN,NaN,0.5,0.5,4.5,Sunderland,SUN,Midfielder,MID
665,646,549940,Fofana,Malick,Fofana,20,56,3,55,0,...,NaN,NaN,NaN,0.5,0.5,5.5,Sunderland,SUN,Midfielder,MID
666,651,661313,J.Angulo,Juan,Angulo,20,56,4,45,0,...,NaN,NaN,NaN,0.5,0.5,4.5,Sunderland,SUN,Forward,FWD
667,668,604211,Tutierov,Tymur,Tutierov,20,56,3,50,0,...,NaN,NaN,NaN,1.6,1.6,5.0,Sunderland,SUN,Midfielder,MID

In [13]:
print(f"Shape: {players.shape}")
players[["web_name", "team_name", "position", "price"]].head()

Shape: (668, 59)

       web_name team_name    position  price
0          Raya   Arsenal  Goalkeeper    6.1
1  Arrizabalaga   Arsenal  Goalkeeper    4.9
2       Meslier   Arsenal  Goalkeeper    4.9
3       Gabriel   Arsenal    Defender    7.9
4      J.Timber   Arsenal    Defender    6.5

In [14]:
# available, unavailable, doubtful, injured, suspended
players["status"].value_counts()

status
a    464
u    106
i     64
d     29
s      5
Name: count, dtype: int64

In [15]:
# handling missing values
mask = players["status"] == "a"

# using df.loc to get these specific rows
players.loc[mask, "chance_of_playing_this_round"] = players.loc[mask, "chance_of_playing_this_round"].fillna(100)
players.loc[mask, "chance_of_playing_next_round"] = players.loc[mask, "chance_of_playing_next_round"].fillna(100)

players[["status", "chance_of_playing_this_round", "chance_of_playing_next_round"]]

    status  chance_of_playing_this_round  chance_of_playing_next_round
0        a                         100.0                         100.0
1        a                         100.0                         100.0
2        a                         100.0                         100.0
3        a                         100.0                         100.0
4        a                         100.0                         100.0
..     ...                           ...                           ...
663      a                         100.0                         100.0
664      a                         100.0                         100.0
665      a                         100.0                         100.0
666      a                         100.0                         100.0
667      a                         100.0                         100.0

[668 rows x 3 columns]

In [16]:
players["points_per_million"] = players["total_points"] / players["price"]
players[["total_points", "price", "points_per_million"]]

     total_points  price  points_per_million
0              42    6.1            6.885246
1               0    4.9            0.000000
2               0    4.9            0.000000
3              35    7.9            4.430380
4               3    6.5            0.461538
..            ...    ...                 ...
663             0    4.5            0.000000
664             1    4.5            0.222222
665             4    5.5            0.727273
666             1    4.5            0.222222
667             1    5.0            0.200000

[668 rows x 3 columns]

In [17]:
top_10_points = players.loc[mask].sort_values("total_points", ascending=False)
top_10_points = top_10_points[["web_name", "team_name_short", "position", "price", "total_points", "points_per_million"]].head(10)
top_10_points = top_10_points.round({"points_per_million": 2})

top_10_points

,web_name,team_name_short,position,price,total_points,points_per_million
127,De Cuyper,BHA,Defender,5.3,59,11.13
136,Groß,BHA,Midfielder,6.2,58,9.35
491,Haaland,MCI,Forward,15.7,58,3.69
151,Vuskovic,BHA,Defender,5.1,51,10.00
184,João Pedro,CHE,Forward,7.9,47,5.95
272,Tarkowski,EVE,Defender,6.2,46,7.42
403,Bogle,LEE,Defender,4.7,45,9.57
482,Cherki,MCI,Midfielder,8.0,44,5.50
7,Calafiori,ARS,Defender,6.0,44,7.33
0,Raya,ARS,Goalkeeper,6.1,42,6.89

In [18]:
top_10_ppm = players.loc[mask].sort_values("points_per_million", ascending=False)
# we add this filter to make the rankings reliable since someone scoring within their 20 mins playing time isnt exactly a reliable pattern
top_10_ppm = top_10_ppm[top_10_ppm["minutes"] > 300]
top_10_ppm = top_10_ppm[["web_name", "team_name_short", "position", "price", "total_points", "points_per_million"]].head(10)
top_10_ppm = top_10_ppm.round({"points_per_million": 2})

top_10_ppm

,web_name,team_name_short,position,price,total_points,points_per_million
127,De Cuyper,BHA,Defender,5.3,59,11.13
151,Vuskovic,BHA,Defender,5.1,51,10.00
403,Bogle,LEE,Defender,4.7,45,9.57
136,Groß,BHA,Midfielder,6.2,58,9.35
351,Tzolakis,HUL,Goalkeeper,4.7,39,8.30
123,Verbruggen,BHA,Goalkeeper,4.6,38,8.26
199,Thomas,COV,Defender,4.0,31,7.75
325,Egan,HUL,Defender,4.1,31,7.56
126,Boscagli,BHA,Defender,4.5,34,7.56
405,Justin,LEE,Defender,4.5,34,7.56

In [19]:
import plotly.express as px

In [20]:
fig = px.scatter(
    players[players["minutes"] > 0],
    x="price",
    y="total_points",
    color="position",
    hover_name="web_name",
    hover_data=["team_name_short", "minutes"],
    labels={"price": "Price (£)", "total_points": "Total Points", "position": "Position"},
    title="FPL Player Prices vs Total Points",
    size="selected_by_percent",
    trendline="ols"
)
fig.show()

In [21]:
active = players[players["minutes"] > 0]
active.groupby("position").apply(lambda g: g["price"].corr(g["total_points"]))

/tmp/ipykernel_3481/3736655123.py:2: DeprecationWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

position
Defender      0.320419
Forward       0.644011
Goalkeeper    0.538262
Midfielder    0.530557
dtype: float64

In [22]:
trap_mask = (players["selected_by_percent"] > 15) & (players["total_points"] < 30)
trap_players = players[trap_mask].copy()
trap_players["xg_diff"] = trap_players["goals_scored"] - trap_players["expected_goals"]
trap_players[["web_name", "status", "selected_by_percent", "clean_sheets", "goals_conceded", "bonus", "defensive_contribution", "xg_diff", "team_name_short", "position", "news", "price", "expected_goals", "minutes", "total_points"]]

,web_name,status,selected_by_percent,clean_sheets,goals_conceded,bonus,defensive_contribution,xg_diff,team_name_short,position,news,price,expected_goals,minutes,total_points
26,Konsa,a,18.5,2,5,3,38,-0.23,ARS,Defender,,4.6,0.23,461,25
436,Virgil,a,15.1,3,8,0,65,-0.31,LIV,Defender,,6.4,0.31,630,29
448,Szoboszlai,i,16.8,3,4,1,47,-0.52,LIV,Midfielder,Hamstring injury - Unknown return date,6.8,1.52,471,21
605,Dubravka,a,16.4,0,0,0,0,0.00,TOT,Goalkeeper,,4.0,0.00,0,0

In [23]:
xGI_mask = (players["minutes"] > 0) & (players["position"] != "Goalkeeper")
players[xGI_mask].groupby("position").apply(lambda g: g["price"].corr(g["expected_goal_involvements"], method="spearman"))

/tmp/ipykernel_3481/2083525947.py:2: DeprecationWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

position
Defender      0.281645
Forward       0.513717
Midfielder    0.553541
dtype: float64

In [24]:
xGI_mask = (players["minutes"] > 0) & (players["position"] != "Goalkeeper") & (players["web_name"] != "Haaland")
players[xGI_mask].groupby("position").apply(lambda g: g["price"].corr(g["expected_goal_involvements"]))

/tmp/ipykernel_3481/2061732862.py:2: DeprecationWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

position
Defender      0.306172
Forward       0.512126
Midfielder    0.621749
dtype: float64

In [25]:
fig = px.scatter(
    players[xGI_mask],
    x="price",
    y="expected_goal_involvements",
    color="position",
    hover_name="web_name",
    hover_data=["team_name_short", "minutes"],
    labels={"price": "Price (£)", "expected_goal_involvements": "Expected Goal Involvements", "position": "Position"},
    title="FPL Player Prices vs Total Points",
    size="selected_by_percent",
    trendline="ols"
)
fig.show()

In [26]:
players["xg_diff"] = players["goals_scored"] - players["expected_goals"]
players[players["minutes"] > 300].sort_values("xg_diff")

,id,code,web_name,first_name,second_name,team,team_code,element_type,now_cost,cost_change_start,...,direct_freekicks_order,ep_this,ep_next,price,team_name,team_name_short,position,position_short,points_per_million,xg_diff
115,106,502500,Thiago,Igor Thiago,Nascimento Rodrigues,4,94,4,78,-2,...,NaN,4.0,4.0,7.8,Brentford,BRE,Forward,FWD,2.307692,-2.69
312,569,551466,Gonzalo,Gonzalo,García,10,54,4,61,1,...,NaN,2.0,2.0,6.1,Fulham,FUL,Forward,FWD,2.950820,-2.46
554,464,216646,Wissa,Yoane,Wissa,17,4,4,61,1,...,NaN,1.5,1.5,6.1,Newcastle,NEW,Forward,FWD,2.950820,-1.97
289,249,586309,Barry,Thierno,Barry,9,11,4,57,2,...,NaN,4.0,4.0,5.7,Everton,EVE,Forward,FWD,4.912281,-1.70
75,67,499604,Rayan,Rayan Vitor,Simplício Rocha,3,91,3,63,-2,...,NaN,2.5,2.5,6.3,Bournemouth,BOU,Midfielder,MID,2.380952,-1.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,40,244850,Rogers,Morgan,Rogers,6,8,3,80,5,...,3.0,5.5,5.5,8.0,Chelsea,CHE,Midfielder,MID,5.000000,1.93
184,165,475168,João Pedro,João Pedro,Junqueira de Jesus,6,8,4,79,4,...,NaN,7.0,7.0,7.9,Chelsea,CHE,Forward,FWD,5.949367,1.95
334,286,540324,Belloumi,Mohamed,Belloumi,11,88,3,52,2,...,2.0,4.0,4.0,5.2,Hull City,HUL,Midfielder,MID,7.500000,2.04
491,411,223094,Haaland,Erling,Haaland,15,43,4,157,2,...,NaN,9.5,9.5,15.7,Man City,MCI,Forward,FWD,3.694268,2.31
482,399,466052,Cherki,Rayan,Cherki,15,43,3,80,5,...,1.0,5.0,5.0,8.0,Man City,MCI,Midfielder,MID,5.500000,2.70

In [27]:
players[(players["minutes"] > 300) & (players["team_name_short"] == "LIV")][["web_name", "position", "total_points", "defensive_contribution", "clean_sheets", "goals_conceded", "bonus"]]

,web_name,position,total_points,defensive_contribution,clean_sheets,goals_conceded,bonus
430,A.Becker,Goalkeeper,30,0,3,8,5
436,Virgil,Defender,29,65,3,8,0
438,Kerkez,Defender,16,45,2,8,0
442,Jacquet,Defender,30,61,3,8,3
446,Wirtz,Midfielder,25,41,3,6,0
447,Gakpo,Midfielder,32,32,2,4,5
448,Szoboszlai,Midfielder,21,47,3,4,1
452,Mac Allister,Midfielder,14,58,2,6,0
457,Munoz,Midfielder,26,26,1,6,2
459,Isak,Forward,42,7,3,5,11
464,Araujo,Defender,23,32,3,3,1
465,Barcola,Midfielder,13,27,2,4,0

In [28]:
import ipywidgets as widgets
from IPython.display import display

def show_players(position, max_price, min_minutes):
    df = players[(players["position"] == position) & (players["price"] <= max_price) & (players["minutes"] > min_minutes)]
    cols = ["web_name", "team_name_short", "price", "total_points", "xg_diff"]
    display(df.sort_values("total_points", ascending=False)[cols].head(15))

widgets.interact(
    show_players,
    position=["Goalkeeper", "Defender", "Midfielder", "Forward"],
    max_price=(4.0, 20, 0.5),
    min_minutes=(0, 300)
)

interactive(children=(Dropdown(description='position', options=('Goalkeeper', 'Defender', 'Midfielder', 'Forwa…

In [29]:
players["nineties"] = players["minutes"] / 90
players["xgi_per90"] = players["expected_goal_involvements"] / players["nineties"]
players["tp_per90"] = players["total_points"] / players["nineties"]
players["gi_per90"] = (players["goals_scored"] + players["assists"]) / players["nineties"]
players["gi_diff_per90"] = players["gi_per90"] - players["xgi_per90"]

players.head()

,id,code,web_name,first_name,second_name,team,team_code,element_type,now_cost,cost_change_start,...,team_name_short,position,position_short,points_per_million,xg_diff,nineties,xgi_per90,tp_per90,gi_per90,gi_diff_per90
0,1,154561,Raya,David,Raya Martín,1,3,1,61,1,...,ARS,Goalkeeper,GKP,6.885246,0.00,7.000000,0.001429,6.000000,0.0,-0.001429
1,2,109745,Arrizabalaga,Kepa,Arrizabalaga Revuelta,1,3,1,49,-1,...,ARS,Goalkeeper,GKP,0.000000,0.00,0.000000,NaN,NaN,NaN,NaN
2,3,437495,Meslier,Illan,Meslier,1,3,1,49,-1,...,ARS,Goalkeeper,GKP,0.000000,0.00,0.000000,NaN,NaN,NaN,NaN
3,4,226597,Gabriel,Gabriel,dos Santos Magalhães,1,3,2,79,-1,...,ARS,Defender,DEF,4.430380,-0.93,7.000000,0.165714,5.000000,0.0,-0.165714
4,5,445122,J.Timber,Jurriën,Timber,1,3,2,65,0,...,ARS,Defender,DEF,0.461538,0.00,1.722222,0.087097,1.741935,0.0,-0.087097

In [30]:
players[players["minutes"] > 300].sort_values("gi_diff_per90")

,id,code,web_name,first_name,second_name,team,team_code,element_type,now_cost,cost_change_start,...,team_name_short,position,position_short,points_per_million,xg_diff,nineties,xgi_per90,tp_per90,gi_per90,gi_diff_per90
312,569,551466,Gonzalo,Gonzalo,García,10,54,4,61,1,...,FUL,Forward,FWD,2.950820,-2.46,6.611111,0.633782,2.722689,0.151261,-0.482521
304,264,477555,Bobb,Oscar,Bobb,10,54,3,55,0,...,FUL,Midfielder,MID,3.454545,-1.28,5.500000,0.476364,3.454545,0.000000,-0.476364
268,209,242898,Johnson,Brennan,Johnson,9,11,3,59,-1,...,EVE,Midfielder,MID,2.033898,-1.07,3.422222,0.426623,3.506494,0.000000,-0.426623
600,403,510281,Sávio,Sávio,Moreira de Oliveira,19,6,3,65,0,...,TOT,Midfielder,MID,1.538462,-0.54,3.666667,0.406364,2.727273,0.000000,-0.406364
567,167,463034,Delap,Liam,Delap,18,17,4,55,0,...,NFO,Forward,FWD,2.363636,-1.17,4.866667,0.544521,2.671233,0.205479,-0.339041
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,391,477424,Gvardiol,Joško,Gvardiol,15,43,2,58,3,...,MCI,Defender,DEF,7.068966,0.68,5.411111,0.221766,7.577002,0.924025,0.702259
171,148,551210,Hato,Jorrel,Hato,6,8,2,45,0,...,CHE,Defender,DEF,4.222222,-0.01,3.866667,0.059483,4.913793,0.775862,0.716379
184,165,475168,João Pedro,João Pedro,Junqueira de Jesus,6,8,4,79,4,...,CHE,Forward,FWD,5.949367,1.95,5.788889,0.580422,8.119002,1.381958,0.801536
136,124,60307,Groß,Pascal,Groß,5,36,3,62,7,...,BHA,Midfielder,MID,9.354839,0.84,6.777778,0.489836,8.557377,1.327869,0.838033
148,138,647850,Kostoulas,Charalampos,Kostoulas,5,36,4,57,2,...,BHA,Forward,FWD,7.192982,1.17,5.355556,0.364108,7.655602,1.307054,0.942946

In [31]:
players["defcon_per90"] = players["defensive_contribution"] / players["nineties"]
players["xgc_per90"] = players["expected_goals_conceded"] / players["nineties"]
players[(players["minutes"] > 300) & (players["position_short"] == "DEF")].sort_values("defcon_per90")[["web_name", "total_points", "defcon_per90", "team_name"]]

        web_name  total_points  defcon_per90      team_name
328        Coyle            17      3.238636      Hull City
403        Bogle            45      3.333333          Leeds
127    De Cuyper            59      3.568966       Brighton
7      Calafiori            44      3.679727        Arsenal
404  Gudmundsson            19      3.958333          Leeds
..           ...           ...           ...            ...
539       Botman            26     11.285714      Newcastle
642      Mukiele            19     12.166667     Sunderland
199       Thomas            31     12.252836  Coventry City
169       Fofana             8     13.557692        Chelsea
355        Mendy            28     13.805310      Hull City

[87 rows x 4 columns]

In [32]:
import numpy as np

players["xgc_per90"] = players["expected_goals_conceded"] / players["nineties"]

active = players[players["minutes"] >= 300]
for col, name in [("tp_per90", "pos_median_tp90"), ("xgi_per90", "pos_median_xgi90"),
                  ("defcon_per90", "pos_median_dc90"), ("xgc_per90", "pos_median_xgc90")]:
    players[name] = players["position"].map(active.groupby("position")[col].median())

low_pts = players["tp_per90"] < 0.8 * players["pos_median_tp90"]
is_att = players["position"].isin(["Midfielder", "Forward"])
is_def = players["position"] == "Defender"

# attackers: one process signal (underlying involvement is low)
att_poor = players["xgi_per90"] < 0.8 * players["pos_median_xgi90"]

# defenders: count weak signals (team concedes lots of chances, he contributes little)
def_signals = (players["xgc_per90"] > 1.2 * players["pos_median_xgc90"]).astype(int) \
            + (players["defcon_per90"] < 0.8 * players["pos_median_dc90"]).astype(int)

players["diagnosis"] = np.select(
    [
        ~(is_att | is_def),
        low_pts & is_att & att_poor,
        low_pts & is_att & ~att_poor,
        low_pts & is_def & (def_signals == 2),
        low_pts & is_def & (def_signals == 1),
        low_pts & is_def & (def_signals == 0),
    ],
    ["Not assessed", "Trap", "Unlucky", "Trap", "Watch", "Unlucky"],
    default="OK",
)

trap_mask = (players["minutes"] >= 300) & (players["selected_by_percent"] > 10)
cols = ["web_name", "team_name_short", "position", "selected_by_percent",
        "tp_per90", "xgi_per90", "xgc_per90", "defcon_per90", "diagnosis"]
players[trap_mask].sort_values("selected_by_percent", ascending=False)[cols]

,web_name,team_name_short,position,selected_by_percent,tp_per90,xgi_per90,xgc_per90,defcon_per90,diagnosis
491,Haaland,MCI,Forward,77.3,8.432956,0.939257,1.451050,3.925687,OK
184,João Pedro,CHE,Forward,73.7,8.119002,0.580422,1.368138,2.936660,OK
7,Calafiori,ARS,Defender,54.7,6.746167,0.337308,0.809540,3.679727,OK
161,Rogers,CHE,Midfielder,49.4,5.901639,0.506066,1.546230,8.114754,OK
136,Groß,BHA,Midfielder,46.1,8.557377,0.489836,1.473934,5.754098,OK
0,Raya,ARS,Goalkeeper,45.3,6.000000,0.001429,0.792857,0.000000,Not assessed
127,De Cuyper,BHA,Defender,42.0,9.155172,0.403448,1.539310,3.568966,OK
482,Cherki,MCI,Midfielder,39.0,10.102041,0.688776,1.363776,4.132653,OK
176,Palmer,CHE,Midfielder,28.2,5.525040,0.343134,1.528110,6.106624,OK
474,Gvardiol,MCI,Defender,27.6,7.577002,0.221766,1.526489,6.098563,OK
517,B.Fernandes,MUN,Midfielder,26.7,4.714286,0.594286,1.404286,5.857143,OK
418,Calvert-Lewin,LEE,Forward,23.3,4.958264,0.560434,1.217028,4.357262,OK
123,Verbruggen,BHA,Goalkeeper,22.6,5.428571,0.030000,1.451429,0.000000,Not assessed
518,Mbeumo,MUN,Midfielder,21.6,5.857143,0.694286,1.404286,4.285714,OK
3,Gabriel,ARS,Defender,21.1,5.000000,0.165714,0.792857,8.285714,OK
541,Hall,NEW,Defender,20.4,5.007949,0.167409,1.739905,8.871224,OK
26,Konsa,ARS,Defender,18.5,4.880694,0.050759,0.980043,7.418655,OK
14,Ødegaard,ARS,Midfielder,18.3,5.341727,0.566547,0.768885,5.017986,OK
272,Tarkowski,EVE,Defender,18.1,6.571429,0.040000,1.391429,10.714286,OK
471,Guéhi,MCI,Defender,17.7,5.285714,0.210000,1.435714,5.142857,OK
448,Szoboszlai,LIV,Midfielder,16.8,4.012739,0.492994,1.186624,8.980892,OK
436,Virgil,LIV,Defender,15.1,4.142857,0.058571,1.182857,9.285714,OK
105,Schade,BRE,Midfielder,14.8,6.629834,0.376243,1.468508,7.127072,OK
604,Kinsky,TOT,Goalkeeper,14.7,3.285714,0.000000,1.335714,0.000000,Not assessed
351,Tzolakis,HUL,Goalkeeper,14.1,5.571429,0.000000,1.494286,0.000000,Not assessed
459,Isak,LIV,Forward,13.8,7.698574,0.727699,1.228106,1.283096,OK
327,Ajayi,HUL,Defender,13.1,4.477612,0.102985,1.416418,6.119403,OK
554,Wissa,NEW,Forward,12.8,2.664474,0.460362,1.576480,4.588816,Unlucky
76,Tavernier,BOU,Midfielder,12.7,6.585366,0.628746,1.205749,8.937282,OK
582,Gibbs-White,NFO,Midfielder,12.1,5.000000,0.586667,1.196667,4.833333,OK
12,Rice,ARS,Midfielder,11.9,5.482234,0.219289,0.764467,9.289340,OK
11,Saka,ARS,Midfielder,11.7,5.587248,0.729362,0.770134,6.946309,OK
363,Diop,IPS,Defender,10.9,2.428571,0.038571,2.020000,9.000000,Watch
403,Bogle,LEE,Defender,10.7,7.500000,0.330000,0.953333,3.333333,OK
148,Kostoulas,BHA,Forward,10.2,7.655602,0.364108,1.641286,7.282158,OK

# Player Table

In [33]:
import numpy as np
import pandas as pd
import ipywidgets as widgets
from IPython.display import display

cols = ["web_name", "team_name", "position", "price", "total_points", "points_per_million",
        "selected_by_percent", "minutes", "tp_per90", "xgi_per90", "xgc_per90",
        "defcon_per90", "diagnosis", "news"]
player_table = players[cols].copy()

teams = ["All"] + sorted(player_table["team_name"].unique())
round_cols = {"points_per_million": 2, "tp_per90": 2, "xgi_per90": 2,
              "xgc_per90": 2, "defcon_per90": 2}

def show_player_table(position, team, sort_by, max_price, min_minutes):
    mask = (player_table["price"] <= max_price) & (player_table["minutes"] >= min_minutes)
    if position != "All":
        mask &= player_table["position"] == position
    if team != "All":
        mask &= player_table["team_name"] == team

    df = player_table[mask]
    lower_is_better = sort_by in ["xgc_per90", "price"]
    df = df.sort_values(sort_by, ascending=lower_is_better).head(15)
    display(df.round(round_cols))

widgets.interact(
    show_player_table,
    position=["All", "Goalkeeper", "Defender", "Midfielder", "Forward"],
    team=teams,
    sort_by=["total_points", "points_per_million", "selected_by_percent", "price",
             "tp_per90", "xgi_per90", "xgc_per90", "defcon_per90"],
    max_price=widgets.FloatSlider(min=4.0, max=16.0, step=0.5, value=16.0),
    min_minutes=widgets.IntSlider(min=0, max=900, step=30, value=300),
)

interactive(children=(Dropdown(description='position', options=('All', 'Goalkeeper', 'Defender', 'Midfielder',…

In [34]:
raw_teams = pd.DataFrame(data_dict["teams"])
raw_teams.head()

,code,draw,form,id,loss,name,played,points,position,short_name,...,unavailable,win,link_url,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,2,ARS,...,False,0,,4,5,0,0,0,0,1
1,7,0,None,2,0,Aston Villa,0,0,12,AVL,...,False,0,,3,3,0,0,0,0,2
2,91,0,None,3,0,Bournemouth,0,0,15,BOU,...,False,0,,3,3,0,0,0,0,127
3,94,0,None,4,0,Brentford,0,0,6,BRE,...,False,0,,3,3,0,0,0,0,130
4,36,0,None,5,0,Brighton,0,0,3,BHA,...,False,0,,3,4,0,0,0,0,131

In [35]:
raw_teams.columns

Index(['code', 'draw', 'form', 'id', 'loss', 'name', 'played', 'points',
       'position', 'short_name', 'strength', 'team_division', 'unavailable',
       'win', 'link_url', 'strength_overall_home', 'strength_overall_away',
       'strength_attack_home', 'strength_attack_away', 'strength_defence_home',
       'strength_defence_away', 'pulse_id'],
      dtype='object')

In [36]:
team_goals = players.copy().groupby("team_name").apply(lambda g: g[["goals_scored", "expected_goals"]].sum())
team_goals["goal_diff"] = team_goals["goals_scored"] - team_goals["expected_goals"]
team_goals["goal_diff_ratio"] = np.abs(team_goals["goal_diff"]) / team_goals["expected_goals"]
team_goals.sort_values("goal_diff_ratio")

/tmp/ipykernel_3481/3586155587.py:1: DeprecationWarning:

DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

                goals_scored  expected_goals  goal_diff  goal_diff_ratio
team_name
Ipswich Town            11.0           10.75       0.25         0.023256
Brentford               13.0           12.15       0.85         0.069959
Arsenal                 11.0           11.97      -0.97         0.081036
Everton                  8.0            9.25      -1.25         0.135135
Crystal Palace           8.0            9.43      -1.43         0.151644
Coventry City            6.0            7.18      -1.18         0.164345
Hull City                8.0            6.83       1.17         0.171303
Aston Villa              7.0            8.46      -1.46         0.172577
Liverpool                9.0           10.98      -1.98         0.180328
Leeds                    8.0            9.98      -1.98         0.198397
Spurs                    6.0            7.51      -1.51         0.201065
Newcastle               10.0            8.15       1.85         0.226994
Man City                19.0           15.38       3.62         0.235371
Man Utd                  9.0           12.00      -3.00         0.250000
Brighton                20.0           15.27       4.73         0.309758
Bournemouth              8.0           12.42      -4.42         0.355878
Sunderland               6.0           10.62      -4.62         0.435028
Fulham                   6.0           11.02      -5.02         0.455535
Nott'm Forest            5.0           11.76      -6.76         0.574830
Chelsea                 17.0            9.98       7.02         0.703407

In [37]:
response = requests.get("https://fantasy.premierleague.com/api/fixtures/")
fixtures_dict = json.loads(response.text)

for key, value in data_dict.items():
  print(key)

chips
events
game_settings
game_config
phases
teams
total_players
element_stats
element_types
elements

In [38]:
fixtures_df = pd.DataFrame(fixtures_dict)
fixtures_df.columns

Index(['code', 'event', 'finished', 'finished_provisional', 'id',
       'kickoff_time', 'minutes', 'provisional_start_time', 'started',
       'team_a', 'team_a_score', 'team_h', 'team_h_score', 'stats',
       'team_h_difficulty', 'team_a_difficulty', 'pulse_id'],
      dtype='object')

In [39]:
fixtures_df.head()

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,stats,team_h_difficulty,team_a_difficulty,pulse_id
0,2645195,1,True,True,1,2026-08-21T19:00:00Z,90,False,True,7,0.0,1,3.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",2,5,0
1,2645198,1,True,True,4,2026-08-22T11:30:00Z,90,False,True,16,0.0,11,2.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",4,2,0
2,2645197,1,True,True,3,2026-08-22T14:00:00Z,90,False,True,8,0.0,9,2.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",2,3,0
3,2645199,1,True,True,5,2026-08-22T14:00:00Z,90,False,True,20,1.0,12,2.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,2,0
4,2645200,1,True,True,6,2026-08-22T14:00:00Z,90,False,True,13,1.0,18,0.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,3,0

In [40]:
played = fixtures_df[fixtures_df["finished"]].copy()

home = pd.DataFrame({
    "team": played["team_h"],
    "opp": played["team_a"],
    "gf": played["team_h_score"].astype(int),
    "ga": played["team_a_score"].astype(int),
    "venue": "H",
    "event": played["event"],
})

away = pd.DataFrame({
    "team": played["team_a"],
    "opp": played["team_h"],
    "gf": played["team_a_score"].astype(int),
    "ga": played["team_h_score"].astype(int),
    "venue": "A",
    "event": played["event"],
})

results = pd.concat([home, away], ignore_index=True)
results

     team  opp  gf  ga venue  event
0       1    7   3   0     H      1
1      11   16   2   0     H      1
2       9    8   2   0     H      1
3      12   20   2   1     H      1
4      18   13   0   1     H      1
..    ...  ...  ..  ..   ...    ...
135    20    3   0   2     A      7
136     8    5   0   5     A      7
137    16   13   1   1     A      7
138     1   18   1   0     A      7
139     7   19   1   3     A      7

[140 rows x 6 columns]

In [41]:
results["points"] = np.select(
    [
        results["gf"] > results["ga"],
        results["gf"] == results["ga"]
    ],
    [3, 1],
    default=0,
)

results

     team  opp  gf  ga venue  event  points
0       1    7   3   0     H      1       3
1      11   16   2   0     H      1       3
2       9    8   2   0     H      1       3
3      12   20   2   1     H      1       3
4      18   13   0   1     H      1       0
..    ...  ...  ..  ..   ...    ...     ...
135    20    3   0   2     A      7       0
136     8    5   0   5     A      7       0
137    16   13   1   1     A      7       1
138     1   18   1   0     A      7       3
139     7   19   1   3     A      7       0

[140 rows x 7 columns]

In [42]:
team_points = results.copy().groupby("team")[["gf", "ga", "points"]].sum()
team_points["gd"] = team_points["gf"] - team_points["ga"]
team_points

      gf  ga  points  gd
team
1     11   5      18   6
2      7  11       8  -4
3      9  13       6  -4
4     13   8      10   5
5     23   5      16  18
6     17  13      13   4
7      6  14       6  -8
8      9  17       7  -8
9      8   7      10   1
10     7  10       5  -3
11     8   7       9   1
12    11  15       9  -4
13     9   6      10   3
14     9   8      12   1
15    19   7      21  12
16    10  10       7   0
17    10  14       8  -4
18     5   9       5  -4
19     6  10       6  -4
20     6  14       4  -8

In [43]:
all_teams = raw_teams.set_index("id")["name"]
team_points["team_name"] = team_points.index.map(all_teams)
team_points

      gf  ga  points  gd       team_name
team
1     11   5      18   6         Arsenal
2      7  11       8  -4     Aston Villa
3      9  13       6  -4     Bournemouth
4     13   8      10   5       Brentford
5     23   5      16  18        Brighton
6     17  13      13   4         Chelsea
7      6  14       6  -8   Coventry City
8      9  17       7  -8  Crystal Palace
9      8   7      10   1         Everton
10     7  10       5  -3          Fulham
11     8   7       9   1       Hull City
12    11  15       9  -4    Ipswich Town
13     9   6      10   3           Leeds
14     9   8      12   1       Liverpool
15    19   7      21  12        Man City
16    10  10       7   0         Man Utd
17    10  14       8  -4       Newcastle
18     5   9       5  -4   Nott'm Forest
19     6  10       6  -4           Spurs
20     6  14       4  -8      Sunderland

In [44]:
team_points["played"] = results.groupby("team").size()
team_points["gf_per_game"] = team_points["gf"] / team_points["played"]
team_points["ga_per_game"] = team_points["ga"] / team_points["played"]
team_points = team_points.sort_values(["points", "gd", "gf"], ascending=False)
team_points

      gf  ga  points  gd       team_name  played  gf_per_game  ga_per_game
team
15    19   7      21  12        Man City       7     2.714286     1.000000
1     11   5      18   6         Arsenal       7     1.571429     0.714286
5     23   5      16  18        Brighton       7     3.285714     0.714286
6     17  13      13   4         Chelsea       7     2.428571     1.857143
14     9   8      12   1       Liverpool       7     1.285714     1.142857
4     13   8      10   5       Brentford       7     1.857143     1.142857
13     9   6      10   3           Leeds       7     1.285714     0.857143
9      8   7      10   1         Everton       7     1.142857     1.000000
11     8   7       9   1       Hull City       7     1.142857     1.000000
12    11  15       9  -4    Ipswich Town       7     1.571429     2.142857
17    10  14       8  -4       Newcastle       7     1.428571     2.000000
2      7  11       8  -4     Aston Villa       7     1.000000     1.571429
16    10  10       7   0         Man Utd       7     1.428571     1.428571
8      9  17       7  -8  Crystal Palace       7     1.285714     2.428571
3      9  13       6  -4     Bournemouth       7     1.285714     1.857143
19     6  10       6  -4           Spurs       7     0.857143     1.428571
7      6  14       6  -8   Coventry City       7     0.857143     2.000000
10     7  10       5  -3          Fulham       7     1.000000     1.428571
18     5   9       5  -4   Nott'm Forest       7     0.714286     1.285714
20     6  14       4  -8      Sunderland       7     0.857143     2.000000

In [45]:
xg = players.groupby("team")["expected_goals"].sum()
team_points["xg"] = team_points.index.map(xg)
team_points["gf_minus_xg"] = team_points["gf"] - team_points["xg"]

team_points.sort_values("gf_minus_xg", ascending=False)

,gf,ga,points,gd,team_name,played,gf_per_game,ga_per_game,xg,gf_minus_xg
team,,,,,,,,,,
5,23,5,16,18,Brighton,7,3.285714,0.714286,15.27,7.73
6,17,13,13,4,Chelsea,7,2.428571,1.857143,9.98,7.02
15,19,7,21,12,Man City,7,2.714286,1.000000,15.38,3.62
17,10,14,8,-4,Newcastle,7,1.428571,2.000000,8.15,1.85
11,8,7,9,1,Hull City,7,1.142857,1.000000,6.83,1.17
4,13,8,10,5,Brentford,7,1.857143,1.142857,12.15,0.85
12,11,15,9,-4,Ipswich Town,7,1.571429,2.142857,10.75,0.25
8,9,17,7,-8,Crystal Palace,7,1.285714,2.428571,9.43,-0.43
1,11,5,18,6,Arsenal,7,1.571429,0.714286,11.97,-0.97
13,9,6,10,3,Leeds,7,1.285714,0.857143,9.98,-0.98
7,6,14,6,-8,Coventry City,7,0.857143,2.000000,7.18,-1.18
9,8,7,10,1,Everton,7,1.142857,1.000000,9.25,-1.25
2,7,11,8,-4,Aston Villa,7,1.000000,1.571429,8.46,-1.46
19,6,10,6,-4,Spurs,7,0.857143,1.428571,7.51,-1.51
14,9,8,12,1,Liverpool,7,1.285714,1.142857,10.98,-1.98
16,10,10,7,0,Man Utd,7,1.428571,1.428571,12.00,-2.00
3,9,13,6,-4,Bournemouth,7,1.285714,1.857143,12.42,-3.42
10,7,10,5,-3,Fulham,7,1.000000,1.428571,11.02,-4.02
20,6,14,4,-8,Sunderland,7,0.857143,2.000000,10.62,-4.62
18,5,9,5,-4,Nott'm Forest,7,0.714286,1.285714,11.76,-6.76

# Official Team Rankings

In [46]:
fig = px.bar(
    team_points.sort_values("gf_minus_xg"),
    orientation="h",
    x="gf_minus_xg",
    y="team_name",
    color="gf_minus_xg"
)
fig.show()

In [47]:
fig = px.scatter(
    team_points,
    x="xg",
    y="gf",
    text="team_name",
)

fig.add_shape(type="line", x0=5, y0=5, x1=16, y1=16)
fig.show()

In [48]:
team_points

,gf,ga,points,gd,team_name,played,gf_per_game,ga_per_game,xg,gf_minus_xg
team,,,,,,,,,,
15,19,7,21,12,Man City,7,2.714286,1.000000,15.38,3.62
1,11,5,18,6,Arsenal,7,1.571429,0.714286,11.97,-0.97
5,23,5,16,18,Brighton,7,3.285714,0.714286,15.27,7.73
6,17,13,13,4,Chelsea,7,2.428571,1.857143,9.98,7.02
14,9,8,12,1,Liverpool,7,1.285714,1.142857,10.98,-1.98
4,13,8,10,5,Brentford,7,1.857143,1.142857,12.15,0.85
13,9,6,10,3,Leeds,7,1.285714,0.857143,9.98,-0.98
9,8,7,10,1,Everton,7,1.142857,1.000000,9.25,-1.25
11,8,7,9,1,Hull City,7,1.142857,1.000000,6.83,1.17
12,11,15,9,-4,Ipswich Town,7,1.571429,2.142857,10.75,0.25
17,10,14,8,-4,Newcastle,7,1.428571,2.000000,8.15,1.85
2,7,11,8,-4,Aston Villa,7,1.000000,1.571429,8.46,-1.46
16,10,10,7,0,Man Utd,7,1.428571,1.428571,12.00,-2.00
8,9,17,7,-8,Crystal Palace,7,1.285714,2.428571,9.43,-0.43
3,9,13,6,-4,Bournemouth,7,1.285714,1.857143,12.42,-3.42
19,6,10,6,-4,Spurs,7,0.857143,1.428571,7.51,-1.51
7,6,14,6,-8,Coventry City,7,0.857143,2.000000,7.18,-1.18
10,7,10,5,-3,Fulham,7,1.000000,1.428571,11.02,-4.02
18,5,9,5,-4,Nott'm Forest,7,0.714286,1.285714,11.76,-6.76
20,6,14,4,-8,Sunderland,7,0.857143,2.000000,10.62,-4.62

In [49]:
all_fixtures = fixtures_df.copy()

home = pd.DataFrame({
    "team": all_fixtures["team_h"],
    "opp": all_fixtures["team_a"],
    "event": all_fixtures["event"],
    "finished": all_fixtures["finished"],
    "difficulty": all_fixtures["team_h_difficulty"],
    "gf": all_fixtures["team_h_score"],
    "ga": all_fixtures["team_a_score"],
    "venue": "H",
})

away = pd.DataFrame({
    "team": all_fixtures["team_a"],
    "opp": all_fixtures["team_h"],
    "event": all_fixtures["event"],
    "finished": all_fixtures["finished"],
    "difficulty": all_fixtures["team_a_difficulty"],
    "gf": all_fixtures["team_a_score"],
    "ga": all_fixtures["team_h_score"],
    "venue": "A",
})

fixtures_long = pd.concat([home, away], ignore_index=True)
fixtures_long

     team  opp  event  finished  difficulty   gf   ga venue
0       1    7      1      True           2  3.0  0.0     H
1      11   16      1      True           4  2.0  0.0     H
2       9    8      1      True           2  2.0  0.0     H
3      12   20      1      True           3  2.0  1.0     H
4      18   13      1      True           3  0.0  1.0     H
..    ...  ...    ...       ...         ...  ...  ...   ...
755    17   11     38     False           2  NaN  NaN     A
756     9   12     38     False           2  NaN  NaN     A
757     3   14     38     False           4  NaN  NaN     A
758    10   16     38     False           4  NaN  NaN     A
759    15   20     38     False           3  NaN  NaN     A

[760 rows x 8 columns]

In [50]:
id_to_name = raw_teams.set_index("id")["name"]
fixtures_long["team_name"] = fixtures_long["team"].map(id_to_name)
fixtures_long["opp_name"] = fixtures_long["opp"].map(id_to_name)

In [51]:
fixtures_long

,team,opp,event,finished,difficulty,gf,ga,venue,team_name,opp_name
0,1,7,1,True,2,3.0,0.0,H,Arsenal,Coventry City
1,11,16,1,True,4,2.0,0.0,H,Hull City,Man Utd
2,9,8,1,True,2,2.0,0.0,H,Everton,Crystal Palace
3,12,20,1,True,3,2.0,1.0,H,Ipswich Town,Sunderland
4,18,13,1,True,3,0.0,1.0,H,Nott'm Forest,Leeds
...,...,...,...,...,...,...,...,...,...,...
755,17,11,38,False,2,NaN,NaN,A,Newcastle,Hull City
756,9,12,38,False,2,NaN,NaN,A,Everton,Ipswich Town
757,3,14,38,False,4,NaN,NaN,A,Bournemouth,Liverpool
758,10,16,38,False,4,NaN,NaN,A,Fulham,Man Utd
759,15,20,38,False,3,NaN,NaN,A,Man City,Sunderland

In [52]:
grid = fixtures_long.pivot(index="team_name", columns="event", values="difficulty")
grid.shape

(20, 38)

In [53]:
grid

event,1,2,3,4,5,6,7,8,9,10,...,29,30,31,32,33,34,35,36,37,38
team_name,,,,,,,,,,,,,,,,,,,,,
Arsenal,2,3,4,3,4,3,3,3,4,2,...,4,3,2,3,3,2,3,3,3,3
Aston Villa,4,4,2,3,3,3,3,4,2,4,...,2,3,3,5,2,3,3,3,5,2
Bournemouth,5,3,3,3,4,4,3,4,3,2,...,3,3,4,3,4,2,4,3,4,4
Brentford,2,3,3,3,4,3,4,2,3,4,...,3,3,3,3,2,5,3,4,2,4
Brighton,3,4,3,2,4,3,2,4,5,3,...,3,2,3,4,3,3,3,3,4,5
Chelsea,3,3,5,2,3,3,3,2,4,3,...,4,2,2,4,4,4,3,3,3,3
Coventry City,5,2,5,3,3,3,3,2,3,3,...,4,4,4,2,3,4,3,2,3,3
Crystal Palace,3,4,3,2,3,3,4,3,3,4,...,2,2,3,5,4,3,3,3,3,3
Everton,2,3,4,3,2,2,4,5,3,2,...,4,2,3,3,3,3,2,4,4,2
Fulham,4,3,2,4,4,2,2,2,3,3,...,3,4,4,3,3,3,2,2,2,4
Hull City,4,2,3,4,3,3,3,3,2,5,...,3,4,4,2,3,3,3,2,3,3
Ipswich Town,3,4,4,3,3,2,5,3,2,3,...,4,2,3,4,3,3,3,4,3,3
Leeds,3,3,4,3,2,5,4,3,3,2,...,3,3,3,3,4,2,4,4,3,3
Liverpool,3,3,2,2,3,4,3,3,4,3,...,2,3,3,3,3,4,5,3,4,3
Man City,3,3,2,4,3,4,2,3,3,3,...,2,4,3,2,4,3,4,2,3,3
Man Utd,2,2,3,4,3,2,3,3,4,3,...,3,5,2,2,2,2,3,3,3,2
Newcastle,4,3,3,3,2,2,3,3,3,3,...,3,3,4,2,2,3,2,3,2,2
Nott'm Forest,3,4,2,3,2,3,4,2,3,4,...,3,3,3,4,3,4,2,5,2,2
Spurs,3,3,3,3,3,4,2,4,2,3,...,3,3,3,3,2,5,4,2,4,3
Sunderland,2,2,3,4,5,3,3,3,2,4,...,3,5,2,3,3,3,4,3,3,4

Cell labels. Add a cell_text column to fixture_long. For finished matches use the score, like MCI 2-1 (H). For upcoming ones, just the opponent and venue, like ARS (A). You’ll need short names for the opponent, so make a second lookup from short_name the same way you made id_to_name. A hint for the logic: np.where(fixture_long["finished"], score_text, upcoming_text).

In [54]:
fixtures_long.head()

,team,opp,event,finished,difficulty,gf,ga,venue,team_name,opp_name
0,1,7,1,True,2,3.0,0.0,H,Arsenal,Coventry City
1,11,16,1,True,4,2.0,0.0,H,Hull City,Man Utd
2,9,8,1,True,2,2.0,0.0,H,Everton,Crystal Palace
3,12,20,1,True,3,2.0,1.0,H,Ipswich Town,Sunderland
4,18,13,1,True,3,0.0,1.0,H,Nott'm Forest,Leeds

In [55]:
id_to_short = raw_teams.set_index("id")["short_name"]

opp_short = fixtures_long["opp"].map(id_to_short)
venue = fixtures_long["venue"]
gf = fixtures_long["gf"].astype("Int64")   # whole numbers that allow missing values
ga = fixtures_long["ga"].astype("Int64")

score_text = opp_short + " " + gf.astype(str) + "-" + ga.astype(str) + " (" + venue + ")"
upcoming_text = opp_short + " (" + venue + ")"

fixtures_long["cell_text"] = np.where(fixtures_long["finished"], score_text, upcoming_text)
fixtures_long.head()

,team,opp,event,finished,difficulty,gf,ga,venue,team_name,opp_name,cell_text
0,1,7,1,True,2,3.0,0.0,H,Arsenal,Coventry City,COV 3-0 (H)
1,11,16,1,True,4,2.0,0.0,H,Hull City,Man Utd,MUN 2-0 (H)
2,9,8,1,True,2,2.0,0.0,H,Everton,Crystal Palace,CRY 2-0 (H)
3,12,20,1,True,3,2.0,1.0,H,Ipswich Town,Sunderland,SUN 2-1 (H)
4,18,13,1,True,3,0.0,1.0,H,Nott'm Forest,Leeds,LEE 0-1 (H)

In [56]:
diff_grid = fixtures_long.pivot(index="team_name", columns="event", values="difficulty")
text_grid = fixtures_long.pivot(index="team_name", columns="event", values="cell_text")

In [57]:
text_grid.loc[:, 5]

team_name
Arsenal           BHA 0-3 (A)
Aston Villa       TOT 3-2 (A)
Bournemouth       LIV 0-1 (H)
Brentford         CHE 3-0 (H)
Brighton          ARS 3-0 (H)
Chelsea           BRE 0-3 (A)
Coventry City     NFO 1-0 (A)
Crystal Palace    LEE 0-0 (A)
Everton           IPS 1-0 (H)
Fulham            MUN 1-1 (H)
Hull City         NEW 1-2 (A)
Ipswich Town      EVE 0-1 (A)
Leeds             CRY 0-0 (H)
Liverpool         BOU 1-0 (A)
Man City          SUN 5-3 (H)
Man Utd           FUL 1-1 (A)
Newcastle         HUL 2-1 (H)
Nott'm Forest     COV 0-1 (H)
Spurs             AVL 2-3 (H)
Sunderland        MCI 3-5 (A)
Name: 5, dtype: object

In [58]:
import plotly.graph_objects as go

fig = go.Figure(go.Heatmap(
    z=diff_grid.values,
    x=diff_grid.columns,
    y=diff_grid.index,
    text=text_grid.values,
    texttemplate="%{text}",
    colorscale=[[0, "green"], [0.5, "yellow"], [1, "red"]],
    zmin=1, zmax=5,
))
fig.update_yaxes(autorange="reversed")
fig.show()

In [59]:
fx = fixtures_df[fixtures_df["event"].notna()].copy()   # drop unscheduled matches
fx["event"] = fx["event"].astype(int)

fx["home"] = fx["team_h"].map(id_to_name)
fx["away"] = fx["team_a"].map(id_to_name)

h = fx["team_h_score"].astype("Int64").astype(str)
a = fx["team_a_score"].astype("Int64").astype(str)
fx["score"] = np.where(fx["started"], h + " - " + a, "v")

fx["kickoff"] = pd.to_datetime(fx["kickoff_time"], utc=True).dt.tz_convert("Asia/Kolkata")
fx["kickoff_text"] = fx["kickoff"].dt.strftime("%a %d %b, %H:%M")

fx = fx.rename(columns={"team_h_difficulty": "home_diff", "team_a_difficulty": "away_diff"})
fx.head()

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,...,team_h_score,stats,home_diff,away_diff,pulse_id,home,away,score,kickoff,kickoff_text
0,2645195,1,True,True,1,2026-08-21T19:00:00Z,90,False,True,7,...,3.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",2,5,0,Arsenal,Coventry City,3 - 0,2026-08-22 00:30:00+05:30,"Sat 22 Aug, 00:30"
1,2645198,1,True,True,4,2026-08-22T11:30:00Z,90,False,True,16,...,2.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",4,2,0,Hull City,Man Utd,2 - 0,2026-08-22 17:00:00+05:30,"Sat 22 Aug, 17:00"
2,2645197,1,True,True,3,2026-08-22T14:00:00Z,90,False,True,8,...,2.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",2,3,0,Everton,Crystal Palace,2 - 0,2026-08-22 19:30:00+05:30,"Sat 22 Aug, 19:30"
3,2645199,1,True,True,5,2026-08-22T14:00:00Z,90,False,True,20,...,2.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,2,0,Ipswich Town,Sunderland,2 - 1,2026-08-22 19:30:00+05:30,"Sat 22 Aug, 19:30"
4,2645200,1,True,True,6,2026-08-22T14:00:00Z,90,False,True,13,...,0.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,3,0,Nott'm Forest,Leeds,0 - 1,2026-08-22 19:30:00+05:30,"Sat 22 Aug, 19:30"

In [60]:
default_gw = int(fx.loc[~fx["finished"], "event"].min())
default_gw

8

# Gameweek Display

In [61]:
def show_gameweek(event):
  cols = ["kickoff_text", "home", "score", "away", "home_diff", "away_diff"]
  df = fx[fx["event"] == event].sort_values("kickoff")[cols]

  styled = df.style.background_gradient(cmap="RdYlGn_r", subset=["home_diff", "away_diff"], vmin=1, vmax=5)
  display(styled)

widgets.interact(
    show_gameweek,
    event=widgets.Dropdown(options=list(range(1, 39)), value=default_gw),
    teams=teams
)

interactive(children=(Dropdown(description='event', index=7, options=(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1…

In [62]:
import plotly.graph_objects as go
import ipywidgets as widgets
from IPython.display import display

def show_heatmap(gw_range, team):
    start, end = gw_range
    d = diff_grid.loc[:, start:end]
    t = text_grid.loc[:, start:end]

    if team != "All":
        d = d.loc[[team]]
        t = t.loc[[team]]

    fig = go.Figure(go.Heatmap(
        z=d.values,
        x=[f"GW{c}" for c in d.columns],
        y=d.index,
        text=t.values,
        texttemplate="%{text}",
        colorscale=[[0, "green"], [0.5, "yellow"], [1, "red"]],
        zmin=1, zmax=5,
    ))
    fig.update_yaxes(autorange="reversed")
    fig.update_layout(height=max(250, 28 * len(d) + 120))
    fig.show()

widgets.interact(
    show_heatmap,
    gw_range=widgets.IntRangeSlider(
        value=[default_gw, min(default_gw + 4, 38)],
        min=1, max=38, step=1,
        description="Gameweeks",
        continuous_update=False,
    ),
    team=["All"] + sorted(diff_grid.index),
)

interactive(children=(IntRangeSlider(value=(8, 12), continuous_update=False, description='Gameweeks', max=38, …

In [63]:
players.head()

,id,code,web_name,first_name,second_name,team,team_code,element_type,now_cost,cost_change_start,...,tp_per90,gi_per90,gi_diff_per90,defcon_per90,xgc_per90,pos_median_tp90,pos_median_xgi90,pos_median_dc90,pos_median_xgc90,diagnosis
0,1,154561,Raya,David,Raya Martín,1,3,1,61,1,...,6.000000,0.0,-0.001429,0.000000,0.792857,3.431843,0.001429,0.000000,1.443571,Not assessed
1,2,109745,Arrizabalaga,Kepa,Arrizabalaga Revuelta,1,3,1,49,-1,...,NaN,NaN,NaN,NaN,NaN,3.431843,0.001429,0.000000,1.443571,Not assessed
2,3,437495,Meslier,Illan,Meslier,1,3,1,49,-1,...,NaN,NaN,NaN,NaN,NaN,3.431843,0.001429,0.000000,1.443571,Not assessed
3,4,226597,Gabriel,Gabriel,dos Santos Magalhães,1,3,2,79,-1,...,5.000000,0.0,-0.165714,8.285714,0.792857,3.605769,0.102574,7.190722,1.465586,OK
4,5,445122,J.Timber,Jurriën,Timber,1,3,2,65,0,...,1.741935,0.0,-0.087097,4.645161,1.538710,3.605769,0.102574,7.190722,1.465586,Watch

In [64]:
players[["web_name", "selected_by_percent", "total_points"]].sort_values("selected_by_percent", ascending=False).head(10)

       web_name  selected_by_percent  total_points
491     Haaland                 77.3            58
184  João Pedro                 73.7            47
7     Calafiori                 54.7            44
161      Rogers                 49.4            40
136        Groß                 46.1            58
0          Raya                 45.3            42
127   De Cuyper                 42.0            59
482      Cherki                 39.0            44
176      Palmer                 28.2            38
474    Gvardiol                 27.6            41

In [65]:
players["net_transfers_event"] = players["transfers_in_event"] - players["transfers_out_event"]
players[["web_name", "team_name_short", "position", "price", "selected_by_percent", "net_transfers_event"]].sort_values("net_transfers_event", ascending=False).head(10)

,web_name,team_name_short,position,price,selected_by_percent,net_transfers_event
76,Tavernier,BOU,Midfielder,6.2,12.7,526453
161,Rogers,CHE,Midfielder,8.0,49.4,257854
136,Groß,BHA,Midfielder,6.2,46.1,253741
127,De Cuyper,BHA,Defender,5.3,42.0,249683
482,Cherki,MCI,Midfielder,8.0,39.0,244966
176,Palmer,CHE,Midfielder,9.8,28.2,231493
518,Mbeumo,MUN,Midfielder,7.9,21.6,227797
177,Neto,CHE,Midfielder,6.5,3.4,198651
459,Isak,LIV,Forward,9.0,13.8,183596
87,Evanilson,BOU,Forward,6.1,5.6,169712

In [66]:
players[["web_name", "team_name_short", "position", "price", "selected_by_percent", "net_transfers_event", "news"]].sort_values("net_transfers_event", ascending=False).tail(10)

,web_name,team_name_short,position,price,selected_by_percent,net_transfers_event,news
160,Martinez,CHE,Goalkeeper,5.0,3.8,-83010,Head injury - Unknown return date
28,Tzolis,ARS,Midfielder,6.2,4.4,-89806,Hamstring injury - Expected back 1 Nov
289,Barry,EVE,Forward,5.7,7.8,-96038,
514,Shaw,MUN,Defender,4.3,5.0,-102292,Unspecified injury - Unknown return date
474,Gvardiol,MCI,Defender,5.8,27.6,-133121,
554,Wissa,NEW,Forward,6.1,12.8,-302178,
517,B.Fernandes,MUN,Midfielder,11.8,26.7,-456494,
448,Szoboszlai,LIV,Midfielder,6.8,16.8,-538469,Hamstring injury - Unknown return date
11,Saka,ARS,Midfielder,9.6,11.7,-575346,Thigh injury - Unknown return date
480,Semenyo,MCI,Midfielder,8.3,9.3,-575553,Knee injury - Unknown return date

In [67]:
players["net_transfers"] = players["transfers_in"] - players["transfers_out"]
players[["web_name", "team_name_short", "position", "price", "selected_by_percent", "net_transfers", "news"]].sort_values("net_transfers", ascending=False).head(10)

,web_name,team_name_short,position,price,selected_by_percent,net_transfers,news
127,De Cuyper,BHA,Defender,5.3,42.0,3882493,
136,Groß,BHA,Midfielder,6.2,46.1,3533983,
482,Cherki,MCI,Midfielder,8.0,39.0,2888278,
161,Rogers,CHE,Midfielder,8.0,49.4,2823126,
7,Calafiori,ARS,Defender,6.0,54.7,1733415,
541,Hall,NEW,Defender,5.3,20.4,1672618,
176,Palmer,CHE,Midfielder,9.8,28.2,1567788,
474,Gvardiol,MCI,Defender,5.8,27.6,1515229,
105,Schade,BRE,Midfielder,6.2,14.8,1132485,
76,Tavernier,BOU,Midfielder,6.2,12.7,1119642,

In [68]:
players[["web_name", "team_name_short", "position", "price", "selected_by_percent", "net_transfers", "news"]].sort_values("net_transfers", ascending=False).tail(10)

,web_name,team_name_short,position,price,selected_by_percent,net_transfers,news
467,Ndiaye,MCI,Midfielder,5.8,5.4,-981622,
509,Maguire,MUN,Defender,4.7,6.5,-1100252,
607,Pedro Porro,TOT,Defender,5.3,4.7,-1183477,
470,O'Reilly,MCI,Defender,6.3,8.8,-1238463,Back injury - 75% chance of playing
518,Mbeumo,MUN,Midfielder,7.9,21.6,-1436053,
514,Shaw,MUN,Defender,4.3,5.0,-1499888,Unspecified injury - Unknown return date
480,Semenyo,MCI,Midfielder,8.3,9.3,-1544022,Knee injury - Unknown return date
28,Tzolis,ARS,Midfielder,6.2,4.4,-1994900,Hamstring injury - Expected back 1 Nov
517,B.Fernandes,MUN,Midfielder,11.8,26.7,-2463718,
448,Szoboszlai,LIV,Midfielder,6.8,16.8,-2498492,Hamstring injury - Unknown return date

In [69]:
players["price_change"] = players["cost_change_start"] / 10
players[["web_name", "price_change", "total_points"]].sort_values("price_change")

      web_name  price_change  total_points
23    Gyökeres          -0.5             4
620        Tel          -0.4             9
8     Hincapie          -0.3             3
661    Brobbey          -0.3            24
274      Keane          -0.3             1
..         ...           ...           ...
161     Rogers           0.5            40
482     Cherki           0.5            44
7    Calafiori           0.5            44
136       Groß           0.7            58
127  De Cuyper           0.8            59

[668 rows x 3 columns]

In [70]:
players[["web_name", "team_name_short", "selected_by_percent", "total_points", "xgi_per90", "pos_median_xgi90", "diagnosis", "price", "news"]][(players["selected_by_percent"] < 5) & (players["minutes"] > 300)].sort_values(["selected_by_percent", "xgi_per90"], ascending=False).head(10)

,web_name,team_name_short,selected_by_percent,total_points,xgi_per90,pos_median_xgi90,diagnosis,price,news
568,Muñoz,NFO,4.8,8,0.296568,0.102574,Unlucky,5.3,
338,Slater,HUL,4.8,18,0.132308,0.268053,Trap,4.5,
307,King,FUL,4.6,28,0.435182,0.268053,OK,5.6,
292,Leno,FUL,4.5,26,0.000000,0.001429,Not assessed,4.5,
28,Tzolis,ARS,4.4,16,0.183978,0.268053,OK,6.2,Hamstring injury - Expected back 1 Nov
9,White,ARS,4.3,32,0.132353,0.102574,OK,5.4,
99,Ajer,BRE,4.2,30,0.082857,0.102574,OK,4.5,
442,Jacquet,LIV,4.2,30,0.068412,0.102574,OK,5.1,
430,A.Becker,LIV,4.2,30,0.000000,0.001429,Not assessed,5.5,
54,N.Jackson,AVL,4.1,21,0.446137,0.506250,OK,6.6,

# Transfer Table

In [71]:
players["reason"] = np.where(players["news"].fillna("") != "", "injury/news", "form/other")

view_cols = ["web_name", "team_name", "position", "price", "selected_by_percent",
             "net_transfers_event", "price_change", "minutes", "xgi_per90", "reason", "news"]

teams = ["All"] + sorted(player_table["team_name"].unique())

def show_movers(metric, position, team, direction, min_minutes, n):
    mask = (players["minutes"] >= min_minutes)
    if position != "All":
        mask &= players["position"] == position
    if team != "All":
        mask &= players["team_name"] == team

    df = players[mask]
    df = df.sort_values(metric, ascending=(direction == "Lowest"))
    display(df[view_cols].head(n).round({"xgi_per90": 2}))

widgets.interact(
    show_movers,
    metric=["net_transfers_event", "selected_by_percent", "price_change"],
    direction=["Highest", "Lowest"],
    position=["All", "Goalkeeper", "Defender", "Midfielder", "Forward"],
    team=teams,
    n=widgets.IntSlider(min=5, max=30, step=5, value=10),
    min_minutes=widgets.IntSlider(min=0, max=900, step=30, value=0),
)

interactive(children=(Dropdown(description='metric', options=('net_transfers_event', 'selected_by_percent', 'p…

In [72]:
filter = (players["position"] == "Forward") | (players["position"] == "Midfielder") & (players["minutes"] > 300)
filter_df = players[filter]

fig = px.scatter(
    filter_df,
    x="selected_by_percent",
    y="xgi_per90",
    text="web_name",
)

fig.show()

In [73]:
diff_zone = players[
    (players["minutes"] >= 300)
    & (players["position"].isin(["Midfielder", "Forward"]))
    & (players["selected_by_percent"] < 10)
].sort_values("xgi_per90", ascending=False)

diff_zone[["web_name", "team_name", "position", "price", "selected_by_percent",
           "minutes", "xgi_per90", "pos_median_xgi90", "tp_per90", "status", "news"]].head(10).round(2)

,web_name,team_name,position,price,selected_by_percent,minutes,xgi_per90,pos_median_xgi90,tp_per90,status,news
289,Barry,Everton,Forward,5.7,7.8,592,0.74,0.51,4.26,a,
661,Brobbey,Sunderland,Forward,5.7,5.2,399,0.69,0.51,5.41,d,Hamstring injury - 75% chance of playing
312,Gonzalo,Fulham,Forward,6.1,6.5,595,0.63,0.51,2.72,a,
115,Thiago,Brentford,Forward,7.8,8.8,622,0.60,0.51,2.60,a,
584,Ndoye,Nott'm Forest,Midfielder,5.5,0.7,459,0.60,0.27,4.90,a,
209,Rudoni,Coventry City,Midfielder,4.9,0.6,465,0.58,0.27,5.03,a,
447,Gakpo,Liverpool,Midfielder,7.1,6.6,370,0.57,0.27,7.78,a,
651,E.Le Fée,Sunderland,Midfielder,5.7,2.9,608,0.55,0.27,3.55,a,
567,Delap,Nott'm Forest,Forward,5.5,1.9,438,0.54,0.51,2.67,a,
87,Evanilson,Bournemouth,Forward,6.1,5.6,592,0.54,0.51,5.62,a,

In [74]:
players[players["web_name"].isin((["David", "Flemming"]))][["web_name", "position", "price", "minutes", "status", "news", "xgi_per90", "pos_median_xgi90"]]

,web_name,position,price,minutes,status,news,xgi_per90,pos_median_xgi90
152,David,Forward,5.9,23,a,,1.643478,0.50625
398,Flemming,Forward,5.5,91,a,,1.542857,0.50625

In [75]:
raw_events = pd.DataFrame(data_dict["events"])
raw_events.columns

Index(['id', 'name', 'deadline_time', 'release_time', 'average_entry_score',
       'finished', 'data_checked', 'highest_scoring_entry',
       'deadline_time_epoch', 'deadline_time_game_offset', 'highest_score',
       'is_previous', 'is_current', 'is_next', 'cup_leagues_created',
       'h2h_ko_matches_created', 'can_enter', 'can_manage', 'released',
       'ranked_count', 'overrides', 'chip_plays', 'most_selected',
       'most_transferred_in', 'top_element', 'top_element_info',
       'transfers_made', 'most_captained', 'most_vice_captained'],
      dtype='object')

In [76]:
events = raw_events.copy()[["id", "name", "deadline_time", "finished", "average_entry_score", "highest_score", "most_selected", "most_captained", "most_vice_captained", "most_transferred_in", "top_element", "top_element_info", "transfers_made", "chip_plays"]]

In [77]:
events["top_element_info"].head()

0    {'id': 115, 'points': 17}
1    {'id': 426, 'points': 23}
2    {'id': 204, 'points': 15}
3    {'id': 124, 'points': 17}
4    {'id': 552, 'points': 17}
Name: top_element_info, dtype: object

In [78]:
events["chip_plays"].head()

0    [{'chip_name': 'bboost', 'num_played': 814606}...
1    [{'chip_name': 'bboost', 'num_played': 338660}...
2    [{'chip_name': 'bboost', 'num_played': 144735}...
3    [{'chip_name': 'bboost', 'num_played': 170070}...
4    [{'chip_name': 'bboost', 'num_played': 135186}...
Name: chip_plays, dtype: object

In [79]:
id_to_player = players.set_index("id")["web_name"]
cols = ["most_selected", "most_captained", "most_vice_captained", "most_transferred_in", "top_element"]

for col in cols:
  events[col] = events[col][events[col].isnull() == False].astype("int32").map(id_to_player)

events[["most_selected", "most_captained", "most_vice_captained", "most_transferred_in", "top_element"]]

,most_selected,most_captained,most_vice_captained,most_transferred_in,top_element
0,Haaland,Haaland,Raya,Raya,De Cuyper
1,João Pedro,Haaland,Raya,De Cuyper,B.Fernandes
2,Haaland,Haaland,B.Fernandes,Cherki,Mitchell
3,João Pedro,Haaland,João Pedro,Rogers,Groß
4,Haaland,Haaland,B.Fernandes,Gibbs-White,Brobbey
5,Haaland,Haaland,Raya,Groß,Henderson
6,Haaland,Haaland,João Pedro,Cherki,Neto
7,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN

In [80]:
events[events["finished"]].sort_values("average_entry_score", ascending=False)

,id,name,deadline_time,finished,average_entry_score,highest_score,most_selected,most_captained,most_vice_captained,most_transferred_in,top_element,top_element_info,transfers_made,chip_plays
1,2,Gameweek 2,2026-08-28T17:30:00Z,True,81,161.0,João Pedro,Haaland,Raya,De Cuyper,B.Fernandes,"{'id': 426, 'points': 23}",11562127,"[{'chip_name': 'bboost', 'num_played': 338660}..."
3,4,Gameweek 4,2026-09-12T12:30:00Z,True,69,151.0,João Pedro,Haaland,João Pedro,Rogers,Groß,"{'id': 124, 'points': 17}",24092744,"[{'chip_name': 'bboost', 'num_played': 170070}..."
6,7,Gameweek 7,2026-10-17T10:00:00Z,True,59,122.0,Haaland,Haaland,João Pedro,Cherki,Neto,"{'id': 156, 'points': 15}",12547022,"[{'chip_name': 'bboost', 'num_played': 179094}..."
5,6,Gameweek 6,2026-10-10T10:00:00Z,True,58,131.0,Haaland,Haaland,Raya,Groß,Henderson,"{'id': 101, 'points': 18}",19638667,"[{'chip_name': 'bboost', 'num_played': 121353}..."
2,3,Gameweek 3,2026-09-04T17:30:00Z,True,51,119.0,Haaland,Haaland,B.Fernandes,Cherki,Mitchell,"{'id': 204, 'points': 15}",27412065,"[{'chip_name': 'bboost', 'num_played': 144735}..."
0,1,Gameweek 1,2026-08-21T17:30:00Z,True,50,131.0,Haaland,Haaland,Raya,Raya,De Cuyper,"{'id': 115, 'points': 17}",0,"[{'chip_name': 'bboost', 'num_played': 814606}..."
4,5,Gameweek 5,2026-09-18T17:30:00Z,True,48,126.0,Haaland,Haaland,B.Fernandes,Gibbs-White,Brobbey,"{'id': 552, 'points': 17}",18907524,"[{'chip_name': 'bboost', 'num_played': 135186}..."

In [81]:
   fin = events[events["finished"]].copy()
   fin["top_points"] = fin["top_element_info"].apply(lambda d: d["points"])

   fin

,id,name,deadline_time,finished,average_entry_score,highest_score,most_selected,most_captained,most_vice_captained,most_transferred_in,top_element,top_element_info,transfers_made,chip_plays,top_points
0,1,Gameweek 1,2026-08-21T17:30:00Z,True,50,131.0,Haaland,Haaland,Raya,Raya,De Cuyper,"{'id': 115, 'points': 17}",0,"[{'chip_name': 'bboost', 'num_played': 814606}...",17
1,2,Gameweek 2,2026-08-28T17:30:00Z,True,81,161.0,João Pedro,Haaland,Raya,De Cuyper,B.Fernandes,"{'id': 426, 'points': 23}",11562127,"[{'chip_name': 'bboost', 'num_played': 338660}...",23
2,3,Gameweek 3,2026-09-04T17:30:00Z,True,51,119.0,Haaland,Haaland,B.Fernandes,Cherki,Mitchell,"{'id': 204, 'points': 15}",27412065,"[{'chip_name': 'bboost', 'num_played': 144735}...",15
3,4,Gameweek 4,2026-09-12T12:30:00Z,True,69,151.0,João Pedro,Haaland,João Pedro,Rogers,Groß,"{'id': 124, 'points': 17}",24092744,"[{'chip_name': 'bboost', 'num_played': 170070}...",17
4,5,Gameweek 5,2026-09-18T17:30:00Z,True,48,126.0,Haaland,Haaland,B.Fernandes,Gibbs-White,Brobbey,"{'id': 552, 'points': 17}",18907524,"[{'chip_name': 'bboost', 'num_played': 135186}...",17
5,6,Gameweek 6,2026-10-10T10:00:00Z,True,58,131.0,Haaland,Haaland,Raya,Groß,Henderson,"{'id': 101, 'points': 18}",19638667,"[{'chip_name': 'bboost', 'num_played': 121353}...",18
6,7,Gameweek 7,2026-10-17T10:00:00Z,True,59,122.0,Haaland,Haaland,João Pedro,Cherki,Neto,"{'id': 156, 'points': 15}",12547022,"[{'chip_name': 'bboost', 'num_played': 179094}...",15

In [82]:
   chips = fin[["id", "chip_plays"]].explode("chip_plays").reset_index(drop=True)
   chips = pd.concat([chips["id"], pd.json_normalize(chips["chip_plays"])], axis=1)

   chips

    id chip_name  num_played
0    1    bboost      814606
1    1       3xc      250816
2    2    bboost      338660
3    2   freehit       78863
4    2  wildcard      279227
5    2       3xc      233946
6    3    bboost      144735
7    3   freehit      421239
8    3  wildcard      709478
9    3       3xc     1787071
10   4    bboost      170070
11   4   freehit      328740
12   4  wildcard      760682
13   4       3xc      323226
14   5    bboost      135186
15   5   freehit      295196
16   5  wildcard      467900
17   5       3xc      226208
18   6    bboost      121353
19   6   freehit      213008
20   6  wildcard      762489
21   6       3xc       88051
22   7    bboost      179094
23   7   freehit       93126
24   7  wildcard      335228
25   7       3xc      724286

In [83]:
chips["chip_name"].unique()

array(['bboost', '3xc', 'freehit', 'wildcard'], dtype=object)

In [84]:
response = requests.get("https://fantasy.premierleague.com/api/event/4/live/")
week_data = json.loads(response.text)

for key, value in week_data.items():
  print(key)

elements

In [85]:
week_elements = pd.DataFrame(week_data["elements"])
stats = pd.json_normalize(week_elements["stats"])
live_stats = pd.concat([week_elements[["id"]], stats], axis=1)
live_stats = live_stats.merge(
    players[["id", "web_name", "team_name", "position"]],
    on="id", how="left"
)
live_stats

,id,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,...,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,total_points,in_dreamteam,played,web_name,team_name,position
0,1,90,0,0,1,0,0,1,0,0,...,0.00,0.00,0.00,1.80,14,True,True,Raya,Arsenal,Goalkeeper
1,2,0,0,0,0,0,0,0,0,0,...,0.00,0.00,0.00,0.00,0,False,False,Arrizabalaga,Arsenal,Goalkeeper
2,3,0,0,0,0,0,0,0,0,0,...,0.00,0.00,0.00,0.00,0,False,False,Meslier,Arsenal,Goalkeeper
3,4,90,0,0,1,0,0,0,0,1,...,0.02,0.01,0.03,1.80,9,False,True,Gabriel,Arsenal,Defender
4,5,45,0,0,0,0,0,0,0,0,...,0.00,0.01,0.01,1.57,1,False,True,J.Timber,Arsenal,Defender
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
654,655,0,0,0,0,0,0,0,0,0,...,0.00,0.00,0.00,0.00,0,False,False,Gboho,Coventry City,Midfielder
655,656,0,0,0,0,0,0,0,0,0,...,0.00,0.00,0.00,0.00,0,False,False,Mfuni,Coventry City,Defender
656,657,0,0,0,0,0,0,0,0,0,...,0.00,0.00,0.00,0.00,0,False,False,Nunes,Brentford,Midfielder
657,658,0,0,0,0,0,0,0,0,0,...,0.00,0.00,0.00,0.00,0,False,False,Ibrahim,Brighton,Midfielder
658,659,0,0,0,0,0,0,0,0,0,...,0.00,0.00,0.00,0.00,0,False,False,Miley,Newcastle,Midfielder

In [86]:
live_stats[live_stats["web_name"] == "Haaland"]["total_points"].iloc[0]

np.int64(9)

In [87]:
live_stats.sort_values("total_points", ascending=False).head(10)

,id,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,...,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,total_points,in_dreamteam,played,web_name,team_name,position
123,124,90,1,2,1,0,0,0,0,0,...,0.82,0.19,1.01,1.33,17,True,True,Groß,Brighton,Midfielder
329,330,82,1,0,1,0,0,0,0,0,...,0.41,0.05,0.46,0.59,15,True,True,Bogle,Leeds,Defender
93,94,90,2,0,0,2,0,0,0,0,...,0.21,0.10,0.31,1.75,15,True,True,Schade,Brentford,Midfielder
304,305,90,1,2,0,2,0,0,0,0,...,0.52,0.19,0.71,0.62,14,True,True,Davis,Ipswich Town,Defender
0,1,90,0,0,1,0,0,1,0,0,...,0.00,0.00,0.00,1.80,14,True,True,Raya,Arsenal,Goalkeeper
285,286,59,2,0,0,1,0,0,0,0,...,0.17,0.06,0.23,0.26,13,True,True,Belloumi,Hull City,Midfielder
164,165,90,1,1,0,2,0,0,0,0,...,0.29,0.04,0.33,1.38,12,True,True,João Pedro,Chelsea,Forward
115,116,90,1,0,1,0,0,0,0,0,...,0.03,0.03,0.06,1.33,12,True,True,Dunk,Brighton,Defender
315,316,62,1,1,0,1,0,0,0,0,...,0.44,0.05,0.49,0.20,12,True,True,Emersonn,Ipswich Town,Forward
232,233,90,0,0,1,0,0,0,0,0,...,0.00,0.07,0.07,0.69,11,True,True,Mykolenko,Everton,Defender

In [88]:
top10 = live_stats.sort_values("total_points", ascending=False).head(10)
top10 = top10.merge(players[["id", "selected_by_percent"]], on="id", how="left")
top10[["web_name", "total_points", "selected_by_percent"]]

     web_name  total_points  selected_by_percent
0        Groß            17                 46.1
1       Bogle            15                 10.7
2      Schade            15                 14.8
3       Davis            14                  7.4
4        Raya            14                 45.3
5    Belloumi            13                  9.2
6  João Pedro            12                 73.7
7        Dunk            12                  1.4
8    Emersonn            12                  3.6
9   Mykolenko            11                  2.6

In [89]:
fin_summary = fin[["id", "name", "average_entry_score", "highest_score", "top_element", "top_points", "most_captained", "most_selected", "most_transferred_in", "transfers_made"]]
fin_summary

,id,name,average_entry_score,highest_score,top_element,top_points,most_captained,most_selected,most_transferred_in,transfers_made
0,1,Gameweek 1,50,131.0,De Cuyper,17,Haaland,Haaland,Raya,0
1,2,Gameweek 2,81,161.0,B.Fernandes,23,Haaland,João Pedro,De Cuyper,11562127
2,3,Gameweek 3,51,119.0,Mitchell,15,Haaland,Haaland,Cherki,27412065
3,4,Gameweek 4,69,151.0,Groß,17,Haaland,João Pedro,Rogers,24092744
4,5,Gameweek 5,48,126.0,Brobbey,17,Haaland,Haaland,Gibbs-White,18907524
5,6,Gameweek 6,58,131.0,Henderson,18,Haaland,Haaland,Groß,19638667
6,7,Gameweek 7,59,122.0,Neto,15,Haaland,Haaland,Cherki,12547022

# Gameweek Summary

In [90]:
def get_live(gw):
  url = f"https://fantasy.premierleague.com/api/event/{gw}/live/"
  gw_data = json.loads(requests.get(url).text)["elements"]
  live = pd.DataFrame(gw_data)
  stats = pd.json_normalize(live["stats"])
  out = pd.concat([live[["id"]], stats], axis=1)
  return out.merge(players[["id", "web_name", "team_name", "position"]], on="id", how="left")

def show_gameweek_summary(gw):
  row = fin_summary[fin_summary["id"] == gw].iloc[0]
  live = get_live(gw)
  print(f"GW{gw}: average {row['average_entry_score']}, highest {row['highest_score'].astype("int32")}, "
        f"captain {row['most_captained']} ({live[live["web_name"] == row["most_captained"]]["total_points"].iloc[0]} pts), top scorer {row['top_element']} ({row['top_points']} pts), "
        f"most transferred {row['most_transferred_in']}, {row["transfers_made"]} total transfers this week, "
        f"most selected {row['most_selected']}"
        )
  cols = ["web_name", "team_name", "position", "minutes", "goals_scored",
          "assists", "clean_sheets", "bonus", "total_points"]
  display(live.sort_values("total_points", ascending=False)[cols].head(10))

widgets.interact(show_gameweek_summary, gw=widgets.Dropdown(options=list(fin_summary["id"]), value=fin_summary["id"].max()))

interactive(children=(Dropdown(description='gw', index=6, options=(1, 2, 3, 4, 5, 6, 7), value=7), Output()), …

In [91]:
url = f"https://fantasy.premierleague.com/api/element-summary/410/" # example: haaland
data = requests.get(url).json()
data.keys()

dict_keys(['fixtures', 'history', 'history_past'])

In [92]:
player_history = pd.DataFrame(data["history"])
player_history.columns

Index(['element', 'fixture', 'opponent_team', 'total_points', 'was_home',
       'kickoff_time', 'team_h_score', 'team_a_score', 'round', 'modified',
       'minutes', 'goals_scored', 'assists', 'clean_sheets', 'goals_conceded',
       'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards',
       'red_cards', 'saves', 'bonus', 'bps', 'influence', 'creativity',
       'threat', 'ict_index', 'clearances_blocks_interceptions', 'recoveries',
       'tackles', 'defensive_contribution', 'starts', 'expected_goals',
       'expected_assists', 'expected_goal_involvements',
       'expected_goals_conceded', 'value', 'transfers_balance', 'selected',
       'transfers_in', 'transfers_out'],
      dtype='object')

In [93]:
keep = [
    # context
    "round", "opponent_team", "was_home", "kickoff_time", "team_h_score", "team_a_score",
    # playing time
    "minutes", "starts",
    # outcome
    "total_points", "goals_scored", "assists", "clean_sheets", "goals_conceded", "saves", "bonus", "bps",
    # process (underlying stats)
    "expected_goals", "expected_assists", "expected_goal_involvements", "expected_goals_conceded",
    # defensive actions
    "defensive_contribution", "clearances_blocks_interceptions", "tackles", "recoveries",
    # price and crowd
    "value", "selected", "transfers_balance",
]
hist = pd.DataFrame(data["history"])[keep].copy()
hist["price"] = hist["value"] / 10

to_num_cols = ["expected_goals", "expected_assists", "expected_goal_involvements", "expected_goals_conceded"]

for col in to_num_cols:
  hist[col] = pd.to_numeric(hist[col])

hist["opponent_team"] = hist["opponent_team"].map(id_to_name)
kick = pd.to_datetime(hist["kickoff_time"], utc=True).dt.tz_convert("Asia/Kolkata")
hist["kickoff"] = kick
hist["kickoff_text"] = kick.dt.strftime("%a %d %b, %H:%M")

hist["venue"] = np.where(hist["was_home"], "H", "A")

hist

,round,opponent_team,was_home,kickoff_time,team_h_score,team_a_score,minutes,starts,total_points,goals_scored,...,clearances_blocks_interceptions,tackles,recoveries,value,selected,transfers_balance,price,kickoff,kickoff_text,venue
0,1,Bournemouth,True,2026-08-23T13:00:00Z,2,1,0,0,0,0,...,0,0,0,50,1505,0,5.0,2026-08-23 18:30:00+05:30,"Sun 23 Aug, 18:30",H
1,2,Crystal Palace,False,2026-08-28T19:00:00Z,1,4,0,0,0,0,...,0,0,0,50,1523,-207,5.0,2026-08-29 00:30:00+05:30,"Sat 29 Aug, 00:30",A
2,3,Coventry City,True,2026-09-05T14:00:00Z,1,0,0,0,0,0,...,0,0,0,49,1321,-309,4.9,2026-09-05 19:30:00+05:30,"Sat 05 Sep, 19:30",H
3,4,Man Utd,False,2026-09-13T15:30:00Z,0,1,0,0,0,0,...,0,0,0,49,989,-363,4.9,2026-09-13 21:00:00+05:30,"Sun 13 Sep, 21:00",A
4,5,Sunderland,True,2026-09-20T13:00:00Z,5,3,0,0,0,0,...,0,0,0,49,874,-122,4.9,2026-09-20 18:30:00+05:30,"Sun 20 Sep, 18:30",H
5,6,Liverpool,False,2026-10-11T15:30:00Z,0,3,0,0,0,0,...,0,0,0,49,794,-81,4.9,2026-10-11 21:00:00+05:30,"Sun 11 Oct, 21:00",A
6,7,Ipswich Town,True,2026-10-17T14:00:00Z,3,2,0,0,0,0,...,0,0,0,49,773,-29,4.9,2026-10-17 19:30:00+05:30,"Sat 17 Oct, 19:30",H

# Per player details

In [94]:
HIST_KEEP = [
    "round", "opponent_team", "was_home", "kickoff_time", "team_h_score", "team_a_score",
    "minutes", "starts",
    "total_points", "goals_scored", "assists", "clean_sheets", "goals_conceded", "saves", "bonus", "bps",
    "expected_goals", "expected_assists", "expected_goal_involvements", "expected_goals_conceded",
    "defensive_contribution", "clearances_blocks_interceptions", "tackles", "recoveries",
    "value", "selected", "transfers_balance",
]

def to_local(series):
    return pd.to_datetime(series, utc=True).dt.tz_convert("Asia/Kolkata")

def get_player(pid):
    data = requests.get(f"https://fantasy.premierleague.com/api/element-summary/{pid}/").json()
    hist = pd.DataFrame(data["history"])
    if not hist.empty:
        hist = hist[HIST_KEEP].copy()
        hist["price"] = hist["value"] / 10
        for col in ["expected_goals", "expected_assists",
                    "expected_goal_involvements", "expected_goals_conceded"]:
            hist[col] = pd.to_numeric(hist[col])
        hist["opponent_team"] = hist["opponent_team"].map(id_to_name)
        kick = to_local(hist["kickoff_time"])
        hist["kickoff"] = kick
        hist["kickoff_text"] = kick.dt.strftime("%a %d %b, %H:%M")
        hist["venue"] = np.where(hist["was_home"], "H", "A")

    fixtures = pd.DataFrame(data["fixtures"])
    if not fixtures.empty:
        # the opponent is the away team when he is at home, otherwise the home team
        opp_id = fixtures["team_a"].where(fixtures["is_home"], fixtures["team_h"])
        fixtures["opponent"] = opp_id.map(id_to_name)
        fixtures["venue"] = np.where(fixtures["is_home"], "H", "A")
        kick = to_local(fixtures["kickoff_time"])
        fixtures["kickoff_text"] = kick.dt.strftime("%a %d %b, %H:%M").fillna("TBC")
        fixtures = (fixtures[["event_name", "kickoff_text", "opponent", "venue", "difficulty"]]
                    .rename(columns={"event_name": "gameweek"}))

    return hist, fixtures


EXTRA_COLS = {
    "Forward":    ["expected_goals", "expected_assists", "expected_goal_involvements"],
    "Midfielder": ["expected_goals", "expected_assists", "expected_goal_involvements"],
    "Defender":   ["expected_goals_conceded", "defensive_contribution",
                   "clearances_blocks_interceptions", "tackles", "recoveries"],
    "Goalkeeper": ["saves", "expected_goals_conceded"],
}

def show_player(pid):
    p = players.loc[players["id"] == pid].iloc[0]
    print(f"{p['web_name']} | {p['team_name']} | {p['position']} | £{p['price']}m | "
          f"{p['selected_by_percent']}% owned | {p['total_points']} pts | status: {p['status']}")
    if p["news"]:
        print("News:", p["news"])

    hist, fixtures = get_player(pid)
    if hist.empty:
        print("No matches played yet.")
    else:
        base = ["round", "kickoff_text", "opponent_team", "venue", "minutes",
                "total_points", "goals_scored", "assists", "clean_sheets", "bonus", "price"]
        display(hist[base + EXTRA_COLS[p["position"]]].round(2))

        # sum over double gameweeks so each round is one point on the line
        per_round = hist.groupby("round", as_index=False)["total_points"].sum()
        fig = px.line(per_round, x="round", y="total_points", markers=True,
                      title=f"{p['web_name']}: points per gameweek",
                      labels={"round": "Gameweek", "total_points": "Points"})
        fig.show()

    print("Upcoming fixtures")
    if fixtures.empty:
        print("None scheduled.")
    else:
        display(fixtures.style.background_gradient(
            cmap="RdYlGn_r", subset=["difficulty"], vmin=1, vmax=5))

options = [(f"{n} ({t})", i) for n, t, i in
           sorted(zip(players["web_name"], players["team_name_short"], players["id"]))]

widgets.interact(show_player, pid=widgets.Dropdown(options=options, description="Player"))

interactive(children=(Dropdown(description='Player', options=(('A.Becker (LIV)', 350), ('A.García (AVL)', 38),…